### ISSUE TITLE
Dataproc Provided Images Missing Critical Security Updates and Components

### ISSUE THREAD

**Issue by Leectan** [GoogleCloudDataproc/cloud-dataproc#135]
Please see attached image. The assessment done on the image was through Tenable. These are serious flaw that could lead to attackers escalate priviledge and take over the Dataproc cluster. 

I'll be more than happy to elaborate more on this, but this is a critical issue that needs to be remediated immediately as there are customers who are currently running production workload on Dataproc.

<img width="1582" alt="GCP_Dataproc" src="https://user-images.githubusercontent.com/24819052/79150777-53578600-7d97-11ea-9872-b18d4e3cb3cc.png">

**Comment by medb** [comment]
What Dataproc image versions is this? How did you create a cluster?

**Comment by medb** [comment]
In latest supported image versions (1.2-1.5) Dataproc uses much newer Linux Kernel versions that doesn't have this vulnerability:

```
$ gcloud compute ssh kernel-12-m --command="uname -a"
Linux kernel-12-m 4.19.0-0.bpo.8-amd64 #1 SMP Debian 4.19.98-1~bpo9+1 (2020-03-09) x86_64 GNU/Linux

$ gcloud compute ssh kernel-13-m --command="uname -a"
Linux kernel-13-m 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u2~bpo9+1 (2019-11-12) x86_64 GNU/Linux

$ gcloud compute ssh kernel-14-m --command="uname -a"
Linux kernel-14-m 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u2~bpo9+1 (2019-11-12) x86_64 GNU/Linux

$ gcloud compute ssh kernel-15-m --command="uname -a"
Linux kernel-15-m 5.4.0-0.bpo.3-amd64 #1 SMP Debian 5.4.13-1~bpo10+1 (2020-02-07) x86_64 GNU/Linux
```

Please, do not file scary-sounding security-related issues, if you are not sure or do not know what are you doing.
