### ISSUE TITLE
Installing Spark 3.2

### ISSUE THREAD

**Issue by altaetran** [GoogleCloudDataproc/cloud-dataproc#150]
Hi, I am wondering if there are any suggestions on how to install Spark 3.2 on dataproc. I am looking to use the push-based shuffle feature which requires Spark 3.2 and an updated spark-3.2.1-yarn-shuffle.jar file. I was able to install Spark 3.2 on all nodes and have it running. However, rather surprisingly, even after deleting the existing spark-3.1.2-yarn-shuffle.jar file and not replacing it with anything else, the external shuffle service is still running after rebooting all nodes and restarting yarn on the master node, suggesting that there is possibly another reference to this jar, or perhaps the yarn-shuffle jar was included as an uber jar somewhere else. Is there a way to verify the location of any other existing shuffle jar locations? The only thing I need to do is have all yarn node managers reference the new shuffle jar without old references. Thank you for your feedback!

**Comment by altaetran** [comment]
Thank you for your response! I need a managed server unfortunately, as I have custom installations that I need to run (I often chain bioinformatics software for example). Would it be possible to run linux binary files and have custom python installations using serverless spark?

I was able to delete all possible references of the old shuffle jar, and confirmed the node managers failed to run. It seems then that the push-based shuffle feature might have some other incompatibility which is beyond what I can understand.

**Comment by medb** [comment]
You can install all necessary Linux binaries in Dataproc Serverless using [custom container images](https://cloud.google.com/dataproc-serverless/docs/guides/custom-containers).
