### ISSUE TITLE
Avro library version and issues

### ISSUE THREAD

**Issue by Rstar1998** [GoogleCloudDataproc/cloud-dataproc#151]
I am using a Dataproc cluster (2.0 ubuntu ) with hadoop 3.2 and spark 3.1. I have a python code to read avro files from GCS. So I have used 'spark-avro_2.12-3.1.0.jar' but its give some error like method not found etc (java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.DataSourceUtils$.creteDateRebaseFuncInRead ). How to decide which library is compatible to use ?

I am reading using :
`df = spark.read.format("avro").load([ 'file1.avro' , 'file2.avro' ]) `

**Comment by medb** [comment]
You need to use an Avro library that is shipped by Dataproc and located on each Dataproc cluster node local FS in `/usr/lib/spark/external/spark-avro.jar` path.

**Comment by Rstar1998** [comment]
Agreed that dataproc does have that library on that location. But my python code  always gives me this : 

AnalysisException: Failed to find data source: avro. Avro is built-in but external data source module since Spark 2.4. Please deploy the application as per the deployment section of "Apache Avro Data Source Guide".

**Comment by medb** [comment]
Yep, you need to add `/usr/lib/spark/external/spark-avro.jar` jar to your Spark app, either via `--jars` arg or `spark.jars` property:
```
--jars=file:///usr/lib/spark/external/spark-avro.jar
spark.jars=file:///usr/lib/spark/external/spark-avro.jar
```

**Comment by Rstar1998** [comment]
Yupp. Worked. Thanks @medb.
