### ISSUE TITLE
How to install custom libraries from PyPi in serverless Dataproc?

### ISSUE THREAD

**Issue by gomrinal** [GoogleCloudDataproc/cloud-dataproc#160]
Let's say someone wants to install python library like `sentence-transformers`(https://www.sbert.net/) from pypi for ML use cases using pyspark. How can one be able to install that before using serverless DataProc?

**Comment by medb** [comment]
To customize Python environment you can use either a [custom container image](https://cloud.google.com/dataproc-serverless/docs/guides/custom-containers), or leverage one of the [Spark's Python dependencies management options](https://spark.apache.org/docs/latest/api/python/user_guide/python_packaging.html).
