### ISSUE TITLE
In Dataproc HA cluster Resource Managers are not syncing up node details

### ISSUE THREAD

**Issue by abhishek021** [GoogleCloudDataproc/cloud-dataproc#96]
In my Dataproc HA setup, the resource managers are not syncing node details, like which node has been assigned to which node label and thus after restarting resource manager, the node label details are messed up. For example, if a node A was previously assigned to node-label X then after restarting resource manager the same node goes to some other node-label (mostly to default).
yarn-site.xml conf is same for all masters.

**Comment by medb** [comment]
To get help, please, file this issue on Stackoverflow with `google-cloud-dataproc` tag: https://stackoverflow.com/questions/tagged/google-cloud-dataproc
